const FeaturedPropertiesData = [
  {
    id: "1",
     files: ["/assets/property-sample.jpg", "/assets/property-sample.jpg"],
    property: {
      actualPrice: 3000,
      amenities: ["string", "string"],
      areaSqft: 9385,
      bathrooms: 5060,
      bedrooms: 4958,
      category: "cat1",
      constructionStatus: "construnted",
      description: "description",
      furnishing: "furnished",
      ownerId: "8e9d0601-e06c-85b8-efc3-a191891a7318",
      propertyFeatures: ["feature1", "feature2"],
      status: "status",
      title: "title",
      type: "type",
      discountPrice: 50000,
      location: {
        addressLine1: "addressLine1",
        addressLine2: "addressLine2",
        city: "city",
        country: "country",
        landmark: "landmark",
        pincode: "474002",
        state: "MP",
      },
    },
  },
  {
    id: "2",
     files: ["/assets/property-sample.jpg", "/assets/property-sample.jpg","/assets/property-sample.jpg"],
    property: {
      actualPrice: 2500.5,
      amenities: ["Pool", "Gym"],
      areaSqft: 4500,
      bathrooms: 3,
      bedrooms: 4,
      category: "Residential",
      constructionStatus: "Ready to Move",
      description: "Beautiful 4BHK villa with modern interiors.",
      furnishing: "Fully Furnished",
      ownerId: "12345678-abcd-90ef-1234-567890abcdef",
      propertyFeatures: ["Garden", "Parking"],
      status: "Available",
      title: "4 BHK Villa",
      type: "Villa",
      discountPrice: 200.0,
      location: {
        addressLine1: "123 Palm Street",
        addressLine2: "Near Lake View",
        city: "Bangalore",
        country: "India",
        landmark: "Opposite Park",
        pincode: "560001",
        state: "Karnataka",
      },
    },
  },
];
export default FeaturedPropertiesData;
